name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch: 

permissions:
  contents: write  # Grant write permissions to GitHub Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_STATS_PAT }}" \
               -o stats.svg \
               "https://github-readme-stats.vercel.app/api?username=rizwan19947&show_icons=true&count_private=true&theme=radical&include_all_commits=true"
      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rizwan19947/rizwan19947.git HEAD:main

